name = "Brain Regeneration"
license = "MIT"
licenselink = "https://github.com/Human-Singularity/brain-regeneration/blob/main/LICENSE"
description = "Custom theme for the Brain Regeneration Observatory"
homepage = "https://brain-regeneration.com"
min_version = "0.120.0"

[author]
  name = "Bruno Amaral"
  homepage = "https://brunoamaral.eu"
